# Generated by Django 4.2.6 on 2023-11-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_test_datetime_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='accuracy',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
