# Generated by Django 4.2.6 on 2023-11-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_test_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='wpm',
            field=models.IntegerField(),
        ),
    ]
